### ISSUE TITLE
Caveats search keyword takes you to legacy link

### ISSUE THREAD

**Issue by jess-desu** [authzed/docs#142]
Searching for caveats at what seems to be the top level results in a link to the legacy API doc (https://authzed.com/docs/reference/api#caveats) and I would expect it to send me here: https://authzed.com/docs/reference/caveats

Start of search:
![Screenshot 2023-08-23 at 5 28 15 PM](https://github.com/authzed/docs/assets/140121672/bfc8bc10-f698-436d-bb78-edd5f603d931)

Search result top of page:
![Screenshot 2023-08-23 at 5 28 30 PM](https://github.com/authzed/docs/assets/140121672/81eb64c6-db87-4939-8f9a-8c34110fadcd)

Search result bottom of page:
![Screenshot 2023-08-23 at 5 28 40 PM](https://github.com/authzed/docs/assets/140121672/40c08945-1c46-4e23-ab24-0035d7c9a0b1)

Search result bottom of page, expanded:
![Screenshot 2023-08-23 at 5 28 48 PM](https://github.com/authzed/docs/assets/140121672/a3619d1f-6d24-4ebb-8bec-710375d35476)

Where search result should go:
![Screenshot 2023-08-23 at 5 29 04 PM](https://github.com/authzed/docs/assets/140121672/87e5415c-962b-451d-82e6-2ee647d218f3)

**Comment by alecmerdler** [comment]
This appears to be fixed with the new docs.

<img width="693" alt="Screenshot 2024-02-21 at 14 49 14" src="https://github.com/authzed/docs/assets/11700385/f1fcf841-b06a-4069-9984-e2cfe6aaa141">
