### ISSUE TITLE
Links to sections don't scroll the page down to that section

### ISSUE THREAD

**Issue by jzelinskie** [authzed/docs#19]
Originally reported by @ecordell:

Links like https://docs.authzed.com/guides/schema#writing-expected-relations only take you to the top of the page, but if you click on the same link in the table of contents on the right, it does the intended behavior: scrolling to the header.

Browser/OS: Chrome, macOS Monterey

**Comment by samkim** [comment]
Observed this happens on other docusaurus 2.0-x sites as well, both in Chrome and Safari. Works as expected in Firefox though.

**Comment by josephschorr** [comment]
We fixed this by upgrading and fixing the `ClientSideOnly` stuff
