### ISSUE TITLE
fix: Wrong example heading under New Enemy Problem section

### ISSUE THREAD

**Issue by Apoorve73** [authzed/docs#223]
# Overview

[New Enemy Problem](https://authzed.com/docs/spicedb/concepts/zanzibar#new-enemy-problem) section is referring to Zanzibar paper's snippet but the heading of **Example B** is shown in place of **Example A** 

<img width="850" alt="Screenshot 2024-05-03 at 5 57 26 PM" src="https://github.com/authzed/docs/assets/55204045/101c3c88-2b55-4cba-a2a2-8114d2e728b9">

# What's Expected?

Heading for the first example should be `Example A: Neglecting ACL update order` as referred in the [Zanzibar paper here](https://authzed.com/zanzibar/2NIRNVHTLn:0.UvFj1won4:0).

Since,this is just a typo, it won't require a lot of changes. Therefore, I would like to pick this issue and fix. Thanks!

**Comment by samkim** [comment]
Good catch! Please create a PR and I'll work with you to get it merged.

**Comment by samkim** [comment]
Merged, thanks for the contribution!

**Comment by Apoorve73** [comment]
Glad to help 😄
