### ISSUE TITLE
golang client creation example does not build

### ISSUE THREAD

**Issue by ensonic** [authzed/docs#77]
I need to change
https://github.com/authzed/docs/blob/main/docs/guides/first-app.mdx?plain=1#L172
to:
```go
	grpcutil.WithInsecureBearerToken("xxxx"),
	grpc.WithTransportCredentials(insecure.NewCredentials()),
```
(and this needs 2 extra imports). Should I send a PR for the tutorial, or do you want to handle this in the grpcutil module?

The error I otherwise get from `go run xxx.go` is:
```
2022/11/15 16:01:54 unable to initialize client: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials)
exit status 1
```

**Comment by vroldanbet** [comment]
@ensonic good catch, I think it would be ok for now to add the missing ` grpc.WithTransportCredentials(insecure.NewCredentials())` with the extra import. I'd suggest opening an issue in grpcutil to see if there is a way we can abstract that up.
