### ISSUE TITLE
REST postman sample collection has wrong body for Lookup Subjects

### ISSUE THREAD

**Issue by danmunteanuevo** [authzed/docs#89]
The link https://www.postman.com/authzed/workspace/spicedb/request/21043612-bdadf2bc-b239-4bb4-b248-b21bcf676d31
states for Lookup Subjects the body:
`{
    "consistency": {
        "minimizeLatency": true
    },
    "subjectObjectType": "user",
    "permission": "view",
    "resource": {
        "object": {
            "objectType": "document",
            "objectId": "topsecret1"
        }
    }
}`

But it should be without the "object" { }
`{
    "consistency": {
        "minimizeLatency": true
    },
    "subjectObjectType": "user",
    "permission": "view",
    "resource": {
            "objectType": "document",
            "objectId": "topsecret1"
    }
}`

**Comment by dsieczko** [comment]
Thanks @danmunteanuevo! We'll take a look at this.

**Comment by samkim** [comment]
@danmunteanuevo can you provide more context around how you're making Lookup Subject requests eg your HTTP client, spicedb version, and any other relevant info?

I've tested lookup requests against a spicedb 0.14.1 instance and the currently documented message bodies are working as expected for me.

**Comment by danmunteanuevo** [comment]
I am using the latest docker version available: https://hub.docker.com/r/authzed/spicedb/tags whish I believe is version 1.15.0.
If I do a Postman call with the documentation body I receive this error:
`{
    "error": {
        "code": 3,
        "message": "invalid LookupSubjectsRequest.Resource: embedded message failed validation | caused by: invalid ObjectReference.ObjectType: value does not match regex pattern \"^([a-z][a-z0-9_]{1,61}[a-z0-9]/)?[a-z][a-z0-9_]{1,62}[a-z0-9]$\"; invalid ObjectReference.ObjectId: value does not match regex pattern \"^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\\\*)$\"",
        "details": []
    }
}`
If I remove the  "object" { } from the  "resource": and leave only the { "objectType": "document", "objectId": "topsecret1" } 
than it works.

**Comment by samkim** [comment]
🤦 I had been testing Lookup _Resources_ even though I had read your comment about Lookup Subject. 

Yes, you're correct and I've updated the example in our Postman examples to match the API documentation. Thanks!
